repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      # - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii, --no-sort-keys]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --ignore=D, --exclude=tests/]
      # Run the formatter.
      - id: ruff-format
